Lesson02
nsafronova/WebixJet-lessons pull request #2
Opened 2022-11-08 14:08 UTC by nsafronova

2022-11-09 20:09 UTC, HelgaListopad requested changes

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts.js
> +			localId: "mylist",
Можно убрать здесь айдишку (и ниже пустой init)
- не используется
- название не совсем соответствует (layout'у странно давать id mylist)

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +			select: 1,
Лучше `true` (boolean). 
Ожидается именно такой вариант, а 1 косвенно трактуется как true

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +					this.remove(id);
Если contacts это коллекция, почему удаление вызывается на листе?

Если ты сейчас
- удалишь данные из листа
- перейдёшь на другую "страницу"
- вернёшься назад

То в листе будут исходные данные, а это при работе с коллекцией или любой моделью данных проблема.

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
>  		view.parse(contacts);
Если ты создала свойство для доступа к листу, то странно не использовать в следующей строке его же.
```
this.list = this.$$("mylist");
this.list.parse(contacts);
```
А `view` можно вообще убрать

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +			this.app.callEvent("pushToForm", [contacts[--id]]);
1. Это событие в твоём коде ничего не делает - данные в форме ты получаешь по urlChange => getParam

2. Нельзя так работать с данными. Ты пробовала посмотреть, что есть `contacts[--id]` ?
Во-первых, это `undefined`, так как contacts это коллекция, а не массив.
Во-вторых, ID это просто идентификатор строки, и 
    - нельзя полагаться на его конкретное значение,
    - нельзя подразумевать, что это всегда число на оно всегда единицу больше индекса

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +		else this.list.select(1);
`1` это конкретное значение, и на него нельзя полагаться - ты можешь не знать, что на самом деле в этот момент есть в данных. 
Используй `getFirstId` с проверкой на то, что значение вообще вернулось.

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +				else this.list.add(contactsData);
С листом связана коллекция => все операции должны выполняться на коллекции

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +							(item.name.toString().toLowerCase().indexOf(value.toLowerCase()) === 0) return true;
1. Фильтрация (попробуй ввести что-нибудь в поле этого комбо) выдаёт ошибку.
В объекте данных нет поля `name` - используй то, которое успешно брала для темплейта.

2. Я бы смягчила проверку на `!== -1`

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +							(item.name.toString().toLowerCase().indexOf(value.toLowerCase()) === 0) return true;
1. Фильтрация (попробуй ввести что-нибудь в поле этого комбо) выдаёт ошибку.
В объекте данных нет поля `name` - используй то, которое успешно брала для темплейта.

2. Я бы смягчила проверку на `!== -1`

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		});
Нужно удалить
Сюда всегда приходит undefined и код не срабатывает

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		if (url.length > 0) {
1. `url.length` тут не при чём - тебе нужно проверять, есть ли `id`, которое ты получила.
Сейчас у тебя при первом открытии Contacts или при переходе на них из другого вью появляется жёлтое предупреждение об ошибке загрузки данных.
Если ты посмотришь в лог и развернёшь компонент, который туда выносится, то это будет как раз эта форма.
Проблема в том, что даже если проверка на `url.length` пройдена, то это не значит, что в этот момент есть `id`
И если `getParam` вернёт undefined, то и конструкция `view.parse(contacts.getItem(id))` не получит элемент из коллекции и не будет загружать данные как надо.
2. `parse` для прозрачности процесса здесь лучше заменить на `setValue`

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		if (url.length > 0) {
А если после исправлений у тебя в листе выставляется селект на строке, но данные не попадают в форму - то это потому, что в урл во время этого первого селекта не передаётся параметр (опишу в комментариях к листу)

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/dataCountries/DataTable.js
>  						let values = this.$$("inputData").getValue();
Обрати внимание на строку ниже
```js
this.$$("mydata").add({
	Name: values
});
```
Раз у тебя теперь везде коллекции, эта и *любые другие операции с данными* (просмотри свой код) должны вызываться на них

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/dataCountries/statusesTable.js
> +export default class StatusesTable extends JetView {
Ты нигде не используешь этот класс - нужно удалить.
Но зачем он создавался, если всё работало до этого без него (класс DataTable переиспользуется, как и раньше)? Напиши, пожалуйста, в ответе на этот комментаирй, почему так вышло.

2022-11-09 20:09 UTC, HelgaListopad commented on sources/views/contacts/contactsList.js
> +		this.on(this.list, "onAfterSelect", (id) => {
Обработчик `onAfterSelect` лучше задавать на ините. Обрати внимание на порядок срабатывания life-time handlers
https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-handlers#ready

`ready` стоит после `urlChange`, а значит этот обработчик селекта появится у листа после того, как отработал код `urlChange` и выставился начальный селект в лист.
Как результат, в url при первом открытии вьюшки не попадает параметр id (это видно даже по урлу), и селект в листе появится, как и должен, а данных в форме не будет.

2022-11-10 07:55 UTC, nsafronova commented on sources/views/dataCountries/statusesTable.js
> +export default class StatusesTable extends JetView {
Я не создавала его.  Скорее всего, в какой-то момент, когда я начала использовать ctrl+z, курсор на тачпаде сдвинулся с нужного окна на окно структуры и вернул удаленный файл, а из-за того, что существование этого файла ни на что в коде не влияло, я даже не увидела, что он вернулся

2022-11-10 14:43 UTC, HelgaListopad approved these changes

2022-11-10 14:43 UTC, merged